name: Hello world

on:
  push:
    branches:
      - main
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world"
        shell: bash
